In [18]:
data<-read.csv("german_credit_data1.csv",header=T)
data

     X.  Age Sex    Job Housing Saving.accounts Checking.account Credit.amount
1     0  67  male   2   own     NA              little            1169
2     1  22  female 2   own     little          moderate          5951
3     2  49  male   1   own     little          NA                2096
4     3  45  male   2   free    little          little            7882
5     4  53  male   2   free    little          little            4870
6     5  35  male   1   free    NA              NA                9055
7     6  53  male   2   own     quite rich      NA                2835
8     7  35  male   3   rent    little          moderate          6948
9     8  61  male   1   own     rich            NA                3059
10    9  28  male   3   own     little          moderate          5234
11   10  25  female 2   rent    little          moderate          1295
12   11  24  female 2   rent    little          little            4308
13   12  22  female 2   own     little          moderate          1567
14   13  60  male   1   own     little          little            1199
15   14  28  female 2   rent    little          little            1403
16   15  32  female 1   own     moderate        little            1282
17   16  53  male   2   own     NA              NA                2424
18   17  25  male   2   own     NA              little            8072
19   18  44  female 3   free    little          moderate         12579
20   19  31  male   2   own     quite rich      NA                3430
21   20  48  male   2   own     little          NA                2134
22   21  44  male   2   rent    quite rich      little            2647
23   22  48  male   1   rent    little          little            2241
24   23  44  male   2   own     moderate        moderate          1804
25   24  26  male   2   own     NA              NA                2069
26   25  36  male   1   own     little          little            1374
27   26  39  male   1   own     little          NA                 426
28   27  42  female 2   rent    rich            rich               409
29   28  34  male   2   own     little          moderate          2415
30   29  63  male   2   own     little          little            6836
⋮    ⋮   ⋮   ⋮      ⋮   ⋮       ⋮               ⋮                ⋮
971  970 22  male   2   own     moderate        moderate         1514
972  971 43  male   1   own     little          NA               7393
973  972 29  female 0   rent    little          little           1193
974  973 36  male   2   rent    little          little           7297
975  974 33  female 2   own     little          NA               2831
976  975 57  female 1   own     quite rich      rich             1258
977  976 64  female 2   own     little          moderate          753
978  977 42  male   2   own     NA              moderate         2427
979  978 47  male   1   own     little          NA               2538
980  979 25  male   2   rent    moderate        moderate         1264
981  980 49  male   2   own     little          moderate         8386
982  981 33  male   3   rent    little          NA               4844
983  982 28  female 3   own     moderate        rich             2923
984  983 26  male   2   own     little          little           8229
985  984 30  male   1   own     little          NA               2028
986  985 25  female 2   rent    little          little           1433
987  986 33  male   2   own     little          rich             6289
988  987 64  female 2   own     moderate        NA               1409
989  988 29  male   3   free    little          little           6579
990  989 48  male   1   own     little          moderate         1743
991  990 37  male   1   own     NA              NA               3565
992  991 34  male   1   own     moderate        NA               1569
993  992 23  male   1   rent    NA              little           1936
994  993 30  male   3   own     little          little           3959
995  994 50  male   2   own     NA              NA               2390
996  995 31  female 1   own     little          NA               1736
997  996 40  male   3   own     little          little           3857
998  997 38  male   2   own     little          NA                804
999  998 23  male   2   free    little          little           1845
1000 999 27  male   2   own     moderate        moderate         4576
     Duration Purpose             Credit.Risks
1     6       radio/TV            1
2    48       radio/TV            2
3    12       education           1
4    42       furniture/equipment 1
5    24       car                 2
6    36       education           1
7    24       furniture/equipment 1
8    36       car                 1
9    12       radio/TV            1
10   30       car                 2
11   12       car                 2
12   48       business            2
13   12       radio/TV            1
14   24       car                 2
15   15       car                 1
16   24       radio/TV            2
17   24       radio/TV            1
18   30       business            1
19   24       car                 2
20   24       radio/TV            1
21    9       car                 1
22    6       radio/TV            1
23   10       car                 1
24   12       car                 1
25   10       furniture/equipment 1
26    6       furniture/equipment 1
27    6       radio/TV            1
28   12       radio/TV            1
29    7       radio/TV            1
30   60       business            2
⋮    ⋮        ⋮                   ⋮
971  15       repairs             1
972  24       car                 1
973  24       car                 2
974  60       business            2
975  30       radio/TV            1
976  24       radio/TV            1
977   6       radio/TV            1
978  18       business            1
979  24       car                 2
980  15       car                 2
981  30       furniture/equipment 2
982  48       business            2
983  21       car                 1
984  36       car                 2
985  24       furniture/equipment 1
986  15       furniture/equipment 1
987  42       business            1
988  13       radio/TV            1
989  24       car                 1
990  24       radio/TV            1
991  12       education           1
992  15       radio/TV            1
993  18       radio/TV            1
994  36       furniture/equipment 1
995  12       car                 1
996  12       furniture/equipment 1
997  30       car                 1
998  12       radio/TV            1
999  45       radio/TV            2
1000 45       car                 1

In [21]:
data$Sex <- as.character(data$Sex)
data$Housing <- as.character(data$Housing)
data$Saving.accounts <- as.character(data$Saving.accounts)
data$Checking.account <- as.character(data$Checking.account)
data$Purpose  <- as.character(data$Purpose)
str(data)
data

'data.frame':	1000 obs. of  11 variables:
 $ X.              : int  0 1 2 3 4 5 6 7 8 9 ...
 $ Age             : int  67 22 49 45 53 35 53 35 61 28 ...
 $ Sex             : chr  "male" "female" "male" "male" ...
 $ Job             : int  2 2 1 2 2 1 2 3 1 3 ...
 $ Housing         : chr  "own" "own" "own" "free" ...
 $ Saving.accounts : chr  NA "little" "little" "little" ...
 $ Checking.account: chr  "little" "moderate" NA "little" ...
 $ Credit.amount   : int  1169 5951 2096 7882 4870 9055 2835 6948 3059 5234 ...
 $ Duration        : int  6 48 12 42 24 36 24 36 12 30 ...
 $ Purpose         : chr  "radio/TV" "radio/TV" "education" "furniture/equipment" ...
 $ Credit.Risks    : int  1 2 1 1 2 1 1 1 1 2 ...

     X.  Age Sex    Job Housing Saving.accounts Checking.account Credit.amount
1     0  67  male   2   own     NA              little            1169
2     1  22  female 2   own     little          moderate          5951
3     2  49  male   1   own     little          NA                2096
4     3  45  male   2   free    little          little            7882
5     4  53  male   2   free    little          little            4870
6     5  35  male   1   free    NA              NA                9055
7     6  53  male   2   own     quite rich      NA                2835
8     7  35  male   3   rent    little          moderate          6948
9     8  61  male   1   own     rich            NA                3059
10    9  28  male   3   own     little          moderate          5234
11   10  25  female 2   rent    little          moderate          1295
12   11  24  female 2   rent    little          little            4308
13   12  22  female 2   own     little          moderate          1567
14   13  60  male   1   own     little          little            1199
15   14  28  female 2   rent    little          little            1403
16   15  32  female 1   own     moderate        little            1282
17   16  53  male   2   own     NA              NA                2424
18   17  25  male   2   own     NA              little            8072
19   18  44  female 3   free    little          moderate         12579
20   19  31  male   2   own     quite rich      NA                3430
21   20  48  male   2   own     little          NA                2134
22   21  44  male   2   rent    quite rich      little            2647
23   22  48  male   1   rent    little          little            2241
24   23  44  male   2   own     moderate        moderate          1804
25   24  26  male   2   own     NA              NA                2069
26   25  36  male   1   own     little          little            1374
27   26  39  male   1   own     little          NA                 426
28   27  42  female 2   rent    rich            rich               409
29   28  34  male   2   own     little          moderate          2415
30   29  63  male   2   own     little          little            6836
⋮    ⋮   ⋮   ⋮      ⋮   ⋮       ⋮               ⋮                ⋮
971  970 22  male   2   own     moderate        moderate         1514
972  971 43  male   1   own     little          NA               7393
973  972 29  female 0   rent    little          little           1193
974  973 36  male   2   rent    little          little           7297
975  974 33  female 2   own     little          NA               2831
976  975 57  female 1   own     quite rich      rich             1258
977  976 64  female 2   own     little          moderate          753
978  977 42  male   2   own     NA              moderate         2427
979  978 47  male   1   own     little          NA               2538
980  979 25  male   2   rent    moderate        moderate         1264
981  980 49  male   2   own     little          moderate         8386
982  981 33  male   3   rent    little          NA               4844
983  982 28  female 3   own     moderate        rich             2923
984  983 26  male   2   own     little          little           8229
985  984 30  male   1   own     little          NA               2028
986  985 25  female 2   rent    little          little           1433
987  986 33  male   2   own     little          rich             6289
988  987 64  female 2   own     moderate        NA               1409
989  988 29  male   3   free    little          little           6579
990  989 48  male   1   own     little          moderate         1743
991  990 37  male   1   own     NA              NA               3565
992  991 34  male   1   own     moderate        NA               1569
993  992 23  male   1   rent    NA              little           1936
994  993 30  male   3   own     little          little           3959
995  994 50  male   2   own     NA              NA               2390
996  995 31  female 1   own     little          NA               1736
997  996 40  male   3   own     little          little           3857
998  997 38  male   2   own     little          NA                804
999  998 23  male   2   free    little          little           1845
1000 999 27  male   2   own     moderate        moderate         4576
     Duration Purpose             Credit.Risks
1     6       radio/TV            1
2    48       radio/TV            2
3    12       education           1
4    42       furniture/equipment 1
5    24       car                 2
6    36       education           1
7    24       furniture/equipment 1
8    36       car                 1
9    12       radio/TV            1
10   30       car                 2
11   12       car                 2
12   48       business            2
13   12       radio/TV            1
14   24       car                 2
15   15       car                 1
16   24       radio/TV            2
17   24       radio/TV            1
18   30       business            1
19   24       car                 2
20   24       radio/TV            1
21    9       car                 1
22    6       radio/TV            1
23   10       car                 1
24   12       car                 1
25   10       furniture/equipment 1
26    6       furniture/equipment 1
27    6       radio/TV            1
28   12       radio/TV            1
29    7       radio/TV            1
30   60       business            2
⋮    ⋮        ⋮                   ⋮
971  15       repairs             1
972  24       car                 1
973  24       car                 2
974  60       business            2
975  30       radio/TV            1
976  24       radio/TV            1
977   6       radio/TV            1
978  18       business            1
979  24       car                 2
980  15       car                 2
981  30       furniture/equipment 2
982  48       business            2
983  21       car                 1
984  36       car                 2
985  24       furniture/equipment 1
986  15       furniture/equipment 1
987  42       business            1
988  13       radio/TV            1
989  24       car                 1
990  24       radio/TV            1
991  12       education           1
992  15       radio/TV            1
993  18       radio/TV            1
994  36       furniture/equipment 1
995  12       car                 1
996  12       furniture/equipment 1
997  30       car                 1
998  12       radio/TV            1
999  45       radio/TV            2
1000 45       car                 1

In [35]:
data$Sex[data$Sex=="male"] <- 1
data$Sex[data$Sex=="female"] <- 2

data$Housing[data$Housing=="own"] <- 1
data$Housing[data$Housing=="free"] <- 2
data$Housing[data$Housing=="rent"] <- 3

data$Saving.accounts[is.na(data$Saving.accounts)] <- 0
data$Saving.accounts[data$Saving.accounts=="little"] <- 1
data$Saving.accounts[data$Saving.accounts=="moderate"] <- 2
data$Saving.accounts[data$Saving.accounts=="quite rich"] <- 3
data$Saving.accounts[data$Saving.accounts=="rich"] <- 4

data$Checking.account[is.na(data$Checking.account)] <- 0
data$Checking.account[data$Checking.account=="little"] <- 1
data$Checking.account[data$Checking.account=="moderate"] <- 2
data$Checking.account[data$Checking.account=="quite rich"] <- 3
data$Checking.account[data$Checking.account=="rich"] <- 4

data$Purpose[data$Purpose=="radio/TV"] <-1
data$Purpose[data$Purpose=="education"] <-2
data$Purpose[data$Purpose=="furniture/equipment"] <-3
data$Purpose[data$Purpose=="car"] <-4
data$Purpose[data$Purpose=="business"] <-5
data$Purpose[data$Purpose=="repairs"] <-6
data$Purpose[data$Purpose=="domestic appliances"] <-7
data$Purpose[data$Purpose=="vacation/others"] <-8
data

     X.  Age Sex Job Housing Saving.accounts Checking.account Credit.amount
1     0  67  1   2   1       0               1                 1169
2     1  22  2   2   1       1               2                 5951
3     2  49  1   1   1       1               0                 2096
4     3  45  1   2   2       1               1                 7882
5     4  53  1   2   2       1               1                 4870
6     5  35  1   1   2       0               0                 9055
7     6  53  1   2   1       3               0                 2835
8     7  35  1   3   3       1               2                 6948
9     8  61  1   1   1       4               0                 3059
10    9  28  1   3   1       1               2                 5234
11   10  25  2   2   3       1               2                 1295
12   11  24  2   2   3       1               1                 4308
13   12  22  2   2   1       1               2                 1567
14   13  60  1   1   1       1               1                 1199
15   14  28  2   2   3       1               1                 1403
16   15  32  2   1   1       2               1                 1282
17   16  53  1   2   1       0               0                 2424
18   17  25  1   2   1       0               1                 8072
19   18  44  2   3   2       1               2                12579
20   19  31  1   2   1       3               0                 3430
21   20  48  1   2   1       1               0                 2134
22   21  44  1   2   3       3               1                 2647
23   22  48  1   1   3       1               1                 2241
24   23  44  1   2   1       2               2                 1804
25   24  26  1   2   1       0               0                 2069
26   25  36  1   1   1       1               1                 1374
27   26  39  1   1   1       1               0                  426
28   27  42  2   2   3       4               4                  409
29   28  34  1   2   1       1               2                 2415
30   29  63  1   2   1       1               1                 6836
⋮    ⋮   ⋮   ⋮   ⋮   ⋮       ⋮               ⋮                ⋮
971  970 22  1   2   1       2               2                1514
972  971 43  1   1   1       1               0                7393
973  972 29  2   0   3       1               1                1193
974  973 36  1   2   3       1               1                7297
975  974 33  2   2   1       1               0                2831
976  975 57  2   1   1       3               4                1258
977  976 64  2   2   1       1               2                 753
978  977 42  1   2   1       0               2                2427
979  978 47  1   1   1       1               0                2538
980  979 25  1   2   3       2               2                1264
981  980 49  1   2   1       1               2                8386
982  981 33  1   3   3       1               0                4844
983  982 28  2   3   1       2               4                2923
984  983 26  1   2   1       1               1                8229
985  984 30  1   1   1       1               0                2028
986  985 25  2   2   3       1               1                1433
987  986 33  1   2   1       1               4                6289
988  987 64  2   2   1       2               0                1409
989  988 29  1   3   2       1               1                6579
990  989 48  1   1   1       1               2                1743
991  990 37  1   1   1       0               0                3565
992  991 34  1   1   1       2               0                1569
993  992 23  1   1   3       0               1                1936
994  993 30  1   3   1       1               1                3959
995  994 50  1   2   1       0               0                2390
996  995 31  2   1   1       1               0                1736
997  996 40  1   3   1       1               1                3857
998  997 38  1   2   1       1               0                 804
999  998 23  1   2   2       1               1                1845
1000 999 27  1   2   1       2               2                4576
     Duration Purpose Credit.Risks
1     6       1       1
2    48       1       2
3    12       2       1
4    42       3       1
5    24       4       2
6    36       2       1
7    24       3       1
8    36       4       1
9    12       1       1
10   30       4       2
11   12       4       2
12   48       5       2
13   12       1       1
14   24       4       2
15   15       4       1
16   24       1       2
17   24       1       1
18   30       5       1
19   24       4       2
20   24       1       1
21    9       4       1
22    6       1       1
23   10       4       1
24   12       4       1
25   10       3       1
26    6       3       1
27    6       1       1
28   12       1       1
29    7       1       1
30   60       5       2
⋮    ⋮        ⋮       ⋮
971  15       6       1
972  24       4       1
973  24       4       2
974  60       5       2
975  30       1       1
976  24       1       1
977   6       1       1
978  18       5       1
979  24       4       2
980  15       4       2
981  30       3       2
982  48       5       2
983  21       4       1
984  36       4       2
985  24       3       1
986  15       3       1
987  42       5       1
988  13       1       1
989  24       4       1
990  24       1       1
991  12       2       1
992  15       1       1
993  18       1       1
994  36       3       1
995  12       4       1
996  12       3       1
997  30       4       1
998  12       1       1
999  45       1       2
1000 45       4       1

In [36]:
n.points<-1000
sampling.rate <-0.8
num.test.set.labels<- n.points* (1 - sampling.rate)

training<-sample(1:n.points, sampling.rate*n.points, replace=FALSE)
train<-subset(data[training,], select=c(Age,Sex,Job,Housing,Saving.accounts,Checking.account,Duration,Purpose,Credit.amount))

testing<-setdiff(1:n.points,training)
test<-subset(data[testing,], select=c(Age,Sex,Job,Housing,Saving.accounts,Checking.account,Duration,Purpose,Credit.amount))

In [37]:
library(class)

In [39]:
cl<- data$Credit.Risks[training]
true.labels<-data$Credit.Risks[testing]

In [42]:
result <- matrix(c("k","rate"),ncol=2,byrow=TRUE)

In [43]:
for(k in 1:20) {
  predicted.labels <- knn(train,test,cl,k)
  num.incorrect.labels<-sum(predicted.labels !=true.labels)
  misclassification.rate<-num.incorrect.labels/num.test.set.labels
  result <- rbind(result, c(k, misclassification.rate))
}
result

      [,1] [,2]
 [1,] k    rate
 [2,] 1    0.44
 [3,] 2    0.45
 [4,] 3    0.44
 [5,] 4    0.37
 [6,] 5    0.36
 [7,] 6    0.36
 [8,] 7    0.345
 [9,] 8    0.355
[10,] 9    0.335
[11,] 10   0.355
[12,] 11   0.36
[13,] 12   0.35
[14,] 13   0.35
[15,] 14   0.355
[16,] 15   0.325
[17,] 16   0.345
[18,] 17   0.33
[19,] 18   0.335
[20,] 19   0.345
[21,] 20   0.345

In [44]:
sampling.rate <-0.7
num.test.set.labels<- n.points* (1 - sampling.rate)

training<-sample(1:n.points, sampling.rate*n.points, replace=FALSE)
train<-subset(data[training,], select=c(Age,Credit.amount))

testing<-setdiff(1:n.points,training)
test<-subset(data[testing,], select=c(Age,Credit.amount))

cl<- data$Credit.Risks[training]
true.labels<-data$Credit.Risks[testing]

result <- matrix(c("k","rate"),ncol=2,byrow=TRUE)

for(k in 1:20) {
  predicted.labels <- knn(train,test,cl,k)
  num.incorrect.labels<-sum(predicted.labels !=true.labels)
  misclassification.rate<-num.incorrect.labels/num.test.set.labels
  result <- rbind(result, c(k, misclassification.rate))
}
result

      [,1] [,2]
 [1,] k    rate
 [2,] 1    0.42
 [3,] 2    0.423333333333333
 [4,] 3    0.39
 [5,] 4    0.37
 [6,] 5    0.363333333333333
 [7,] 6    0.366666666666667
 [8,] 7    0.35
 [9,] 8    0.346666666666667
[10,] 9    0.34
[11,] 10   0.34
[12,] 11   0.32
[13,] 12   0.34
[14,] 13   0.323333333333333
[15,] 14   0.34
[16,] 15   0.323333333333333
[17,] 16   0.323333333333333
[18,] 17   0.323333333333333
[19,] 18   0.31
[20,] 19   0.31
[21,] 20   0.313333333333333